[package]
name = "boost_variant2"
description = "Boost C++ library boost_variant2 packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_variant2"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_variant2"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_mp11 = { version = "0.1.0", path = "../boost_mp11" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
